dist: trusty
sudo: false
language: python
python: "2.7"
services:
  - postgresql
env:
  - TOX_ENV=py34 GALAXY_VERSION=dev
  - TOX_ENV=py27 GALAXY_VERSION=dev
  - TOX_ENV=py27 GALAXY_VERSION=release_18.05
  - TOX_ENV=py27 GALAXY_VERSION=release_18.01
  - TOX_ENV=py27 GALAXY_VERSION=release_17.09
  - TOX_ENV=py27 GALAXY_VERSION=release_17.05
  - TOX_ENV=py27 GALAXY_VERSION=release_17.01
  - TOX_ENV=py27 GALAXY_VERSION=release_16.10
  - TOX_ENV=py27 GALAXY_VERSION=release_16.07
  - TOX_ENV=py27 GALAXY_VERSION=release_16.04
  - TOX_ENV=py27 GALAXY_VERSION=release_16.01
  - TOX_ENV=py27 GALAXY_VERSION=release_15.10
  - TOX_ENV=py27 GALAXY_VERSION=release_15.07
  - TOX_ENV=py27 GALAXY_VERSION=release_15.05
  - TOX_ENV=py27 GALAXY_VERSION=release_15.03
  - TOX_ENV=py27 GALAXY_VERSION=release_15.01
  - TOX_ENV=py27 GALAXY_VERSION=release_14.10

matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=py36 GALAXY_VERSION=dev
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.6-dev
    - python: "2.7"
      env: TOX_ENV=py35 GALAXY_VERSION=dev
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.5-dev
    - os: osx
      # No version of Python is available via virtualenv on OS X workers, see https://github.com/travis-ci/travis-ci/issues/2312
      language: generic
      env: TOX_ENV=py27 GALAXY_VERSION=dev
      before_install:
        # PostgreSQL on OSX is not started, see https://github.com/travis-ci/travis-ci/issues/1875
        - rm -rf /usr/local/var/postgres
        - initdb /usr/local/var/postgres
        - pg_ctl -D /usr/local/var/postgres start
        - createuser -s postgres
        - virtualenv .venv
        - . .venv/bin/activate

install:
  - pip install "tox>=1.8.0"

before_script:
  # Create a PostgreSQL database for Galaxy. The default SQLite3 database makes test fail randomly because of "database locked" error.
  - createdb -U postgres galaxy-travis
  # Install Galaxy
  - cd $HOME
  - wget https://github.com/galaxyproject/galaxy/archive/${GALAXY_VERSION}.tar.gz
  - tar xvzf ${GALAXY_VERSION}.tar.gz | tail
  # Releases/dev branch are named differently
  - cd galaxy-${GALAXY_VERSION}/
  # Export GALAXY_CONFIG_FILE environment variable to be used by run_galaxy.sh
  - export GALAXY_CONFIG_FILE=config/galaxy.ini
  # Export BIOBLEND_ environment variables to be used in BioBlend tests
  - export BIOBLEND_GALAXY_MASTER_API_KEY=$(LC_ALL=C tr -dc A-Za-z0-9 < /dev/urandom | head -c 32)
  - export BIOBLEND_GALAXY_USER_EMAIL=${USER}@localhost.localdomain
  - DATABASE_CONNECTION=postgresql://postgres:@localhost/galaxy-travis
  - eval "echo \"$(cat "${TRAVIS_BUILD_DIR}/tests/template_galaxy.ini")\"" > "$GALAXY_CONFIG_FILE"
  # Update kombu requirement (and its dependency amqp) to a version compatible with Python 2.7.11, see https://github.com/celery/kombu/pull/540
  - |
    if [ -f eggs.ini ]; then
      sed -i.bak -e 's/^kombu = .*$/kombu = 3.0.30/' -e 's/^amqp = .*$/amqp = 1.4.8/' eggs.ini;
    fi
  # Start Galaxy and wait for successful server start
  - export GALAXY_SKIP_CLIENT_BUILD=1
  - GALAXY_RUN_ALL=1 "${TRAVIS_BUILD_DIR}/run_galaxy.sh" --daemon --wait
  - export BIOBLEND_GALAXY_URL=http://localhost:8080

script:
  # Run nosetests through setuptools, so it will install test depedencies
  - cd $TRAVIS_BUILD_DIR && tox -e $TOX_ENV
