on: [push]
name: lint
jobs:
  Lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: lint
      run: |
        python -m pip install 'tox>=1.8.0' 'virtualenv>=20.0.14'
        tox -e flake8

